#pragma config(Motor,  motorB,          mB,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mC,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int state = 0;

task buttons()
{
	while(1)
	{
		while(nNxtButtonPressed == -1) wait10Msec(1);

		if (nNxtButtonPressed == kRightButton) {
			state++;
			if (state == 3) state = 0;
		}
		if (nNxtButtonPressed == kLeftButton) {
			state--;
			if (state == -1) state = 2;
		}

		while(nNxtButtonPressed != -1) wait10Msec(1);

	}
}

task main()
{
	StartTask(buttons);
	ubyte b[2];
	float ch1, ch2;
	while(1)
	{
		while(cCmdMessageGetSize(mailbox1) < 2) {
			nxtDisplayTextLine(7,"Buffer: %d", cCmdMessageGetSize(mailbox1));
			wait1Msec(1);
		}
		cCmdMessageRead(b, 2, mailbox1);

		switch(state) {
		case 0:

			ch1 = 4 - b[0]/32.0;
			ch2 = 4 - b[1]/32.0;

			motor[mB] = ch1 > 0 ? ch1 * 25 : 0;
			motor[mC] = ch2 > 0 ? ch2 * 25 : 0;

			nxtDisplayTextLine(0,"State 1:");
			nxtDisplayTextLine(1,"Control on effort");
			nxtDisplayTextLine(3,"%d %d",b[0],b[1]);

			break;


		case 1:

			ch1 = b[0]/32.0 - 4;
			ch2 = b[1]/32.0 - 4;

			motor[mB] = ch1 > 0 ? ch1 * 25 : 0;
			motor[mC] = ch2 > 0 ? ch2 * 25 : 0;

			nxtDisplayTextLine(0,"State 2:");
			nxtDisplayTextLine(1,"Control on relax");
			nxtDisplayTextLine(3,"%d %d",b[0],b[1]);

			break;


		case 2:

			ch1 = b[0]/32.0 - 4;

			motor[mB] = ch1 > 0 ? ch1 * 25 : 0;
			motor[mC] = ch1 < 0 ? -ch1 * 25 : 0;

			nxtDisplayTextLine(0,"State 3:");
			nxtDisplayTextLine(1,"One channel");
			nxtDisplayTextLine(3,"%d",b[0]);

			break;
		}

		nxtDisplayTextLine(7,"Buffer: %d", cCmdMessageGetSize(mailbox1));
		wait1Msec(1);
	}
}
